// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: helloworld.proto

package com.example.lib;

/**
* Validates {@code HelloReply} protobuf objects.
*/
public class HelloReplyValidator implements io.envoyproxy.pgv.ValidatorImpl<com.example.lib.HelloReply>{
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		if (clazz.equals(com.example.lib.HelloReply.class)) return new HelloReplyValidator();
		
		return null;
	}
		
	
	

	public void assertValid(com.example.lib.HelloReply proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	// no validation rules for Message

	
	}

}

