// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: helloworld.proto

package com.example.lib;

/**
* Validates {@code HelloRequest} protobuf objects.
*/
public class HelloRequestValidator implements io.envoyproxy.pgv.ValidatorImpl<com.example.lib.HelloRequest>{
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		if (clazz.equals(com.example.lib.HelloRequest.class)) return new HelloRequestValidator();
		
		return null;
	}
		
	
	

	public void assertValid(com.example.lib.HelloRequest proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	
			io.envoyproxy.pgv.StringValidation.minLength(".HelloRequest.name", proto.getName(), 5);
	
	}

}

